--- #YAML:1.0
name:               Test-Subs
version:            0.06
abstract:           Test your modules with a lightweight syntax based on anonymous block
author:
    - Mathias Kende <mathias@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.3002
build_requires:  {}
requires:
    Carp:             0
    Exporter:         0
    Filter::Simple:   0
    List::MoreUtils:  0
    perl:             5.010001
    Pod::Checker:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
